language: php

dist: trusty

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
    - php: 7.1
      env:
        - deps=low
    - php: 7.2
    - php: 7.2
      env:
        - deps=low
    - php: 7.3
    - php: 7.3
      env:
        - deps=low
    - php: 7.4
    - php: 7.4
      env:
        - deps=low
    - php: nightly
    - php: nightly
      env:
        - deps=low
    - php: hhvm
    - php: hhvm-nightly
  # Allow failures until Travis build includes HHVM 3.20.2 which fix the issue with composer (see http://hhvm.com/blog/2017/06/07/hhvm-3-20.html)
  allow_failures:
    - php: 7.4
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true

before_install:
  - if [[ $TRAVIS_PHP_VERSION = hhv* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi;
  - travis_retry composer self-update

install:
  - if [ "$deps" != low ]; then travis_retry composer update --no-interaction --prefer-dist; fi;
  - if [ "$deps" == low ]; then travis_retry composer update --no-interaction --prefer-dist --prefer-lowest; fi;

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' && "$deps" != low ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover --exclude-group integration; fi;
  - if [[ "$TRAVIS_PHP_VERSION" != '7.1' || "$deps" == low ]]; then vendor/bin/phpunit --exclude-group integration; fi;

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' && "$deps" != low ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' && "$deps" != low ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
